# Generated by Django 2.1.7 on 2019-03-13 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recursosBiblio', '0003_auto_20190313_1817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='escrit_per', to='recursosBiblio.Author'),
        ),
    ]
