# Generated by Django 2.1.7 on 2019-03-13 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recursosBiblio', '0005_auto_20190313_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(blank=True, default='1', on_delete=django.db.models.deletion.PROTECT, related_name='escrit_per', to='recursosBiblio.Author'),
        ),
    ]
